import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'
import { StoreProvider } from '@/redux/provider'
import LeftSidebar from '@/components/bars/LeftSidebar'
import Bottombar from '@/components/bars/BottomBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'PIXELVIDEO',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          <Navbar />
          <main className='flex flex-row'>

            <LeftSidebar />

            <section className='w-full'>
              <div >
                {children}
              </div>
            </section>

            <Bottombar />

          </main>
        </StoreProvider>
      </body>
    </html>
  )
}
